export const COMMODITY_GROUPS = [
  { id: '001', name: 'Accommodation Rentals', category: 'General Services' },
  { id: '002', name: 'Membership Fees', category: 'General Services' },
  { id: '003', name: 'Workplace Safety', category: 'General Services' },
  { id: '004', name: 'Consulting', category: 'General Services' },
  { id: '005', name: 'Financial Services', category: 'General Services' },
  { id: '006', name: 'Fleet Management', category: 'General Services' },
  { id: '007', name: 'Recruitment Services', category: 'General Services' },
  { id: '008', name: 'Professional Development', category: 'General Services' },
  { id: '009', name: 'Miscellaneous Services', category: 'General Services' },
  { id: '010', name: 'Insurance', category: 'General Services' },
  { id: '011', name: 'Electrical Engineering', category: 'Facility Management' },
  { id: '012', name: 'Facility Management Services', category: 'Facility Management' },
  { id: '013', name: 'Security', category: 'Facility Management' },
  { id: '014', name: 'Renovations', category: 'Facility Management' },
  { id: '015', name: 'Office Equipment', category: 'Facility Management' },
  { id: '016', name: 'Energy Management', category: 'Facility Management' },
  { id: '017', name: 'Maintenance', category: 'Facility Management' },
  { id: '018', name: 'Cafeteria and Kitchenettes', category: 'Facility Management' },
  { id: '019', name: 'Cleaning', category: 'Facility Management' },
  { id: '020', name: 'Audio and Visual Production', category: 'Publishing Production' },
  { id: '021', name: 'Books/Videos/CDs', category: 'Publishing Production' },
  { id: '022', name: 'Printing Costs', category: 'Publishing Production' },
  { id: '023', name: 'Software Development for Publishing', category: 'Publishing Production' },
  { id: '024', name: 'Material Costs', category: 'Publishing Production' },
  { id: '025', name: 'Shipping for Production', category: 'Publishing Production' },
  { id: '026', name: 'Digital Product Development', category: 'Publishing Production' },
  { id: '027', name: 'Pre-production', category: 'Publishing Production' },
  { id: '028', name: 'Post-production Costs', category: 'Publishing Production' },
  { id: '029', name: 'Hardware', category: 'Information Technology' },
  { id: '030', name: 'IT Services', category: 'Information Technology' },
  { id: '031', name: 'Software', category: 'Information Technology' },
  { id: '032', name: 'Courier, Express, and Postal Services', category: 'Logistics' },
  { id: '033', name: 'Warehousing and Material Handling', category: 'Logistics' },
  { id: '034', name: 'Transportation Logistics', category: 'Logistics' },
  { id: '035', name: 'Delivery Services', category: 'Logistics' },
  { id: '036', name: 'Advertising', category: 'Marketing & Advertising' },
  { id: '037', name: 'Outdoor Advertising', category: 'Marketing & Advertising' },
  { id: '038', name: 'Marketing Agencies', category: 'Marketing & Advertising' },
  { id: '039', name: 'Direct Mail', category: 'Marketing & Advertising' },
  { id: '040', name: 'Customer Communication', category: 'Marketing & Advertising' },
  { id: '041', name: 'Online Marketing', category: 'Marketing & Advertising' },
  { id: '042', name: 'Events', category: 'Marketing & Advertising' },
  { id: '043', name: 'Promotional Materials', category: 'Marketing & Advertising' },
  { id: '044', name: 'Warehouse and Operational Equipment', category: 'Production' },
  { id: '045', name: 'Production Machinery', category: 'Production' },
  { id: '046', name: 'Spare Parts', category: 'Production' },
  { id: '047', name: 'Internal Transportation', category: 'Production' },
  { id: '048', name: 'Production Materials', category: 'Production' },
  { id: '049', name: 'Consumables', category: 'Production' },
  { id: '050', name: 'Maintenance and Repairs', category: 'Production' },
]
